language: java
jdk:
  - openjdk8
  
branches: # branches : Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정한다. 현재 옵션은 오직 master 브랜치에 push될 때만 수행한다.
  only:
    - master

# Travis CI 서버의 Home
cache: # cache : 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    
script: "./gradlew clean build" # script : master 브랜치에 푸시되었을 때 수행하는 명렁어로 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행한다.

before_deploy: # before_deploy : deploy 명령어가 실행되기 전에 수행된다. CodeDeploy는 Jar 파일은 인식하지 못하므로 Jar+기타 설정 파일들을 모아 압축(zip)한다.
#  - zip -r Tutorial-Test * # 현재 위치의 모든 파일을 Tutorial-Test 이름으로 압축(zip)한다. 명령어의 마지막 위치는 본인의 프로젝트 이름이어야 한다.
#  - mkdir -p deploy # deploy라는 디렉토리를 Travis CI가 실행 중인 위치에서 생성한다.
#  - mv Tutorial-Test.zip deploy/Tutorial-Test.zip # Tutorial-Test.zip 파일을 deploy/Tutorial-Test.zip으로 이동시킨다.
  # 수정
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성, Travis CI는 S3로 특정 파일만 업로드가 안된다. 디렉토리 단위로만 업로드할 수 있기 때문에 before-deploy 디렉토리는 항상 생성한다.
  - cp scripts/*.sh before-deploy/ # before-deploy에는 zip 파일에 포함시킬 파일들을 저장한다.
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축, zip -r 명령어를 통해 before-deploy 디렉토리 전체 파일을 압축한다.
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성한다.
  - mv before-deploy/before-deploy.zip deploy/Tutorial-Test.zip # deploy로 zip파일 이동
  
deploy: # deploy : S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언한다.
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    access_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: tutorial-test-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리, 앞에서 생성한 deploy 디렉토리를 지정한다. 해당 위치의 파일들만 S3로 전송한다.
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    access_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: tutorial-test-build # S3 버킷
    key: Tutorial-Test.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: Tutorial-Test # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: Tutorial-Test-group # 웹 콘솔에서 등록한 CodeDeploy 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications: # notifications : Travis CI 실행 완료 시 자동으로 알람이 가도록 설정한다.
  email:
    recipients:
      - hyungjjun.kim@gmail.com