# AWS CodeDeploy 설정 : step3 버전(무중단 배포 추가)

version: 0.0 # CodeDeploy 버전을 이야기한다. 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생한다.
os: linux
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정한다. 루트 경로(/)를 지정하면 전체 파일을 이야기한다.
    destination: /home/ec2-user/app/step3/zip/ # source에서 지정된 파일을 받을 위치이다. 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행된다.
#    overwrite: yes # 기존에 파일들이 있으면 덮어쓸지를 결정한다. 현재 yes라고 했으니 파일들을 덮어쓰게 된다. # codedeploy-agent 업데이트로 인해 옵션 설정 방법 변경되었다.
file_exists_behavior: OVERWRITE  # overwrite: yes 대신 이 옵션으로 대체되었다.

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖고록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어를 지정힌다. ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다. timeout: 60으로 스크립트 실행 60초 이상 수행되면 실패가 된다.(무한정 기다릴 수 없으니 시간 제한을 둬야만 한다)
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ec2-user