server:
  port: 8082
  servlet:
    encoding:
      force: 'true'

spring:
  config:
    activate:
      on-profile: real
  profiles:
    include: oauth, real-db
  session:
    store-type: jdbc          
  jpa: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb